---
spring:
  main:
    allow-bean-definition-overriding: true  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
  datasource:
    claimstore:
      driverClassName: org.postgresql.Driver
      username: ${CLAIM_STORE_DB_USERNAME:-}
      password: ${CLAIM_STORE_DB_PASSWORD:-}
      url: jdbc:postgresql://${CLAIM_STORE_DB_HOST:}:${CLAIM_STORE_DB_PORT:}/${CLAIM_STORE_DB_NAME:claimstore}${CLAIM_STORE_DB_CONNECTION_OPTIONS:}

idam:
  api:
    url: "http://localhost:5000"
  s2s-auth:
    url: "http://localhost:4552"
    totp_secret: "AAAAAAAAAAAAAAAA"
    microservice: "cmc_claim_store"

core_case_data:
  api:
    url: "http://localhost:4452"

feign:
  httpclient:
    enabled: true

oauth2:
  client:
    id: 'cmc_citizen'

migration:
  cases:
    references: 000MC673
    flag: true
    lots:
      size: 0
  fixDataIssues: true
  dryRun: false
  delay:
    between:
      cases:
        lots: 0
