dependencies:
  - name: java
    version: ~2.13.1
    repository: '@hmctspublic'
  - name: postgresql
    version: ~2.6.5
    repository: '@stable'
    tags:
      - cmc-claim-store-postgresql-pod
  - name: cmc-citizen-frontend
    version: ~1.1.0
    repository: '@hmctspublic'
    tags:
      - cmc-citizen-frontend-pod
  - name: ccd
    version: ~3.3.1
    repository: '@hmctspublic'
    tags:
      - cmc-ccd-stack
