dependencies:
  - name: postgresql
    version: ~2.6.5
    repository: '@stable'
  - name: java
    version: 0.0.10
    repository: '@hmcts'
    alias: claim-store
  - name: ccd
    version: 0.4.0
    repository: '@hmcts'
  - name: nodejs
    version: 0.0.11
    repository: '@hmcts'
  - name: feature-toggle-api
    version: 0.0.3
    repository: '@hmcts'
