dependencies:
  - name: java
    version: ~1.1.0
    repository: '@hmcts'
  - name: postgresql
    version: ~2.6.5
    repository: '@stable'
    tags:
      - cmc-claim-store-postgresql-pod
  - name: cmc-citizen-frontend
    version: 0.0.4
    repository: '@hmcts'
    tags:
      - cmc-citizen-frontend-pod
  - name: ccd
    version: ~1.0.0
    repository: '@hmcts'
    tags:
      - cmc-ccd-stack
