postgresql:
  enabled: false
ccd:
  enabled: false

java:
  image: hmctspublic.azurecr.io/cmc/claim-store:latest
  ingressHost: cmc-claim-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4400
  aadIdentityName: money-claims
  keyVaults:
    cmc:
      resourceGroup: cmc
      secrets:
        - AppInsightsInstrumentationKey
        - cmc-db-password
        - citizen-oauth-client-secret
        - claim-store-s2s-secret
        - anonymous-caseworker-username
        - anonymous-caseworker-password
        - system-update-username
        - system-update-password
        - notify-api-key
        - milo-recipient
        - staff-email
        - live-support-email
        - rpa-email-sealed-claim
        - rpa-email-more-time-requested
        - rpa-email-response
        - rpa-email-ccj
        - rpa-email-paid-in-full
  environment:
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: claim-store
    REFORM_ENVIRONMENT: preview
    SPRING_MAIL_HOST: mta.reform.hmcts.net
    SPRING_MAIL_PORT: 25
    SPRING_MAIL_TEST_CONNECTION: false
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mta.reform.hmcts.net
    CLAIM_STORE_TEST_SUPPORT_ENABLED: true
    CMC_DB_USERNAME: 'cmc@cmc-{{ .Values.global.environment }}'
    CMC_DB_HOST: cmc-{{ .Values.global.environment }}.postgres.database.azure.com
    CMC_DB_CONNECTION_OPTIONS: '?sslmode=require'
    CMC_DB_NAME: cmc
    CMC_DB_PORT: 5432
    FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
    STAFF_NOTIFICATIONS_SENDER: noreply@reform.hmcts.net
    RPA_NOTIFICATIONS_SENDER: noreply@reform.hmcts.net
    DOCUMENT_MANAGEMENT_USERROLES: caseworker-cmc,citizen
    MILO_CSV_SCHEDULE: '-'
    MILO_CSV_SENDER: noreply@reform.hmcts.net
    SCHEDULE_STATE_TRANSITION_STAY_CLAIM: '0 0 16 ? * MON-FRI *'
    SCHEDULE_STATE_TRANSITION_WAITING_TRANSFER: '0 0 16 ? * MON-FRI *'
    CLAIM_STAYED_SCHEDULE: ''
    ASYNC_MAX_THREADPOOL_SIZE: 50
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    PDF_SERVICE_URL: http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SEND_LETTER_URL: http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAY_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEES_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FRONTEND_BASE_URL: https://moneyclaims.{{ .Values.global.environment }}.platform.hmcts.net
    RESPOND_TO_CLAIM_URL: https://moneyclaims.{{ .Values.global.environment }}.platform.hmcts.net/first-contact/start
    CORE_CASE_DATA_API_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOC_ASSEMBLY_URL: http://dg-docassembly-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
